/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIsta;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author OWNER
 */
public class Categorias extends javax.swing.JFrame {

    /**
     * Creates new form Categorias
     */
    public Categorias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdlCat = new javax.swing.JDialog();
        txtCodigocat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombrecat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btAgregarCAT = new javax.swing.JButton();
        btCancelarcat = new javax.swing.JButton();
        tituloNuevo = new javax.swing.JLabel();
        tituloModi = new javax.swing.JLabel();
        rbGenerar = new javax.swing.JRadioButton();
        rbEditar = new javax.swing.JRadioButton();
        btgGenerarEditar = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCate = new javax.swing.JTable();
        btNuevoCat = new javax.swing.JButton();
        btEliminarCat = new javax.swing.JButton();
        btmodiCat = new javax.swing.JButton();
        txtBuscarCat = new javax.swing.JTextField();
        btSalirProductos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        btOrdenar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        jdlCat.setResizable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("CODIGO:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("INGRESA EL NOMBRE DE LA CATEGORÍA A CREAR:");

        btAgregarCAT.setText("Agregar");

        btCancelarcat.setText("Salir");

        tituloNuevo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloNuevo.setText("NUEVA CATEGORÍA");

        tituloModi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloModi.setText("Modificar categoría.");

        btgGenerarEditar.add(rbGenerar);
        rbGenerar.setSelected(true);
        rbGenerar.setText("Generar codigos aut.");

        btgGenerarEditar.add(rbEditar);
        rbEditar.setText("Editar codigo");

        javax.swing.GroupLayout jdlCatLayout = new javax.swing.GroupLayout(jdlCat.getContentPane());
        jdlCat.getContentPane().setLayout(jdlCatLayout);
        jdlCatLayout.setHorizontalGroup(
            jdlCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlCatLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jdlCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdlCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombrecat)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jdlCatLayout.createSequentialGroup()
                        .addComponent(txtCodigocat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbGenerar)
                        .addGap(18, 18, 18)
                        .addComponent(rbEditar)))
                .addGap(18, 28, Short.MAX_VALUE)
                .addGroup(jdlCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCancelarcat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAgregarCAT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
            .addGroup(jdlCatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloModi)
                .addGap(18, 18, 18)
                .addComponent(tituloNuevo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdlCatLayout.setVerticalGroup(
            jdlCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdlCatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jdlCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloModi, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdlCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdlCatLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jdlCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigocat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbGenerar)
                            .addComponent(rbEditar)))
                    .addComponent(btAgregarCAT, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jdlCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jdlCatLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombrecat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btCancelarcat, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbCate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Categoria", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(jtbCate);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 104, -1, 350));

        btNuevoCat.setText("Nueva categoria");
        getContentPane().add(btNuevoCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 104, 172, 43));

        btEliminarCat.setText("Eliminar categ.");
        getContentPane().add(btEliminarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 153, 172, 43));

        btmodiCat.setText("Modificar categ.");
        getContentPane().add(btmodiCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 202, 172, 43));
        getContentPane().add(txtBuscarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 56, 346, 30));

        btSalirProductos.setText("SALIR");
        getContentPane().add(btSalirProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 172, 43));

        jLabel4.setFont(new java.awt.Font("Verdana Pro", 1, 24)); // NOI18N
        jLabel4.setText("CATEGORÍAS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 6, -1, -1));

        btBuscar.setText("Buscar catg.");
        getContentPane().add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, 104, 30));

        btOrdenar.setText("Ordenar");
        getContentPane().add(btOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 56, -1, 30));

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 630, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JButton getBtAgregarCAT() {
        return btAgregarCAT;
    }

    public void setBtAgregarCAT(JButton btAgregarCAT) {
        this.btAgregarCAT = btAgregarCAT;
    }

    public JButton getBtCancelarcat() {
        return btCancelarcat;
    }

    public void setBtCancelarcat(JButton btCancelarcat) {
        this.btCancelarcat = btCancelarcat;
    }

    public JButton getBtEliminarCat() {
        return btEliminarCat;
    }

    public void setBtEliminarCat(JButton btEliminarCat) {
        this.btEliminarCat = btEliminarCat;
    }

    public JButton getBtNuevoCat() {
        return btNuevoCat;
    }

    public void setBtNuevoCat(JButton btNuevoCat) {
        this.btNuevoCat = btNuevoCat;
    }

    public JButton getBtSalirProductos() {
        return btSalirProductos;
    }

    public void setBtSalirProductos(JButton btSalirProductos) {
        this.btSalirProductos = btSalirProductos;
    }

    public JButton getBtmodiCat() {
        return btmodiCat;
    }

    public void setBtmodiCat(JButton btmodiCat) {
        this.btmodiCat = btmodiCat;
    }

    public JDialog getJdlCat() {
        return jdlCat;
    }

    public void setJdlCat(JDialog jdlCat) {
        this.jdlCat = jdlCat;
    }

    public JTable getJtbCate() {
        return jtbCate;
    }

    public void setJtbCate(JTable jtbCate) {
        this.jtbCate = jtbCate;
    }

    public JTextField getTxtBuscarCat() {
        return txtBuscarCat;
    }

    public void setTxtBuscarCat(JTextField txtBuscarCat) {
        this.txtBuscarCat = txtBuscarCat;
    }

    public JTextField getTxtCodigocat() {
        return txtCodigocat;
    }

    public void setTxtCodigocat(JTextField txtCodigocat) {
        this.txtCodigocat = txtCodigocat;
    }

    public JTextField getTxtNombrecat() {
        return txtNombrecat;
    }

    public JLabel getTituloModi() {
        return tituloModi;
    }

    public void setTituloModi(JLabel tituloModi) {
        this.tituloModi = tituloModi;
    }

    public JLabel getTituloNuevo() {
        return tituloNuevo;
    }

    public void setTituloNuevo(JLabel tituloNuevo) {
        this.tituloNuevo = tituloNuevo;
    }

    public ButtonGroup getBtgGenerarEditar() {
        return btgGenerarEditar;
    }

    public void setBtgGenerarEditar(ButtonGroup btgGenerarEditar) {
        this.btgGenerarEditar = btgGenerarEditar;
    }

    public JRadioButton getRbEditar() {
        return rbEditar;
    }

    public void setRbEditar(JRadioButton rbEditar) {
        this.rbEditar = rbEditar;
    }

    public JRadioButton getRbGenerar() {
        return rbGenerar;
    }

    public void setRbGenerar(JRadioButton rbGenerar) {
        this.rbGenerar = rbGenerar;
    }

    public JButton getBtBuscar() {
        return btBuscar;
    }

    public void setBtBuscar(JButton btBuscar) {
        this.btBuscar = btBuscar;
    }

    public JButton getBtOrdenar() {
        return btOrdenar;
    }

    public void setBtOrdenar(JButton btOrdenar) {
        this.btOrdenar = btOrdenar;
    }

    /**
     * @param args the command line arguments
     */
    public void setTxtNombrecat(JTextField txtNombrecat) {
        this.txtNombrecat = txtNombrecat;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarCAT;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCancelarcat;
    private javax.swing.JButton btEliminarCat;
    private javax.swing.JButton btNuevoCat;
    private javax.swing.JButton btOrdenar;
    private javax.swing.JButton btSalirProductos;
    private javax.swing.ButtonGroup btgGenerarEditar;
    private javax.swing.JButton btmodiCat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jdlCat;
    private javax.swing.JTable jtbCate;
    private javax.swing.JRadioButton rbEditar;
    private javax.swing.JRadioButton rbGenerar;
    private javax.swing.JLabel tituloModi;
    private javax.swing.JLabel tituloNuevo;
    private javax.swing.JTextField txtBuscarCat;
    private javax.swing.JTextField txtCodigocat;
    private javax.swing.JTextField txtNombrecat;
    // End of variables declaration//GEN-END:variables
}
