/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VIsta;

import com.toedter.calendar.JDateChooser;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JTextPane;

/**
 *
 * @author OWNER
 */
public class RegistrosdeFacturasGastosBalances extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistrosdeFacturasGastoCorriente1
     */
    public RegistrosdeFacturasGastosBalances() {
        initComponents();
    }
    
    
    public JButton getBtPrevisualizar() {
        return btPrevisualizar;
    }

    public void setBtPrevisualizar(JButton btPrevisualizar) {
        this.btPrevisualizar = btPrevisualizar;
    }

    public JButton getBtVerCategoria() {
        return btVerCategoria;
    }

    public void setBtVerCategoria(JButton btVerCategoria) {
        this.btVerCategoria = btVerCategoria;
    }

    public JComboBox<String> getCbProCate() {
        return cbProCate;
    }

    public void setCbProCate(JComboBox<String> cbProCate) {
        this.cbProCate = cbProCate;
    }

    public JDialog getJdGastos() {
        return jdGastos;
    }

    public void setJdGastos(JDialog jdGastos) {
        this.jdGastos = jdGastos;
    }

    public JDialog getJdProductos() {
        return jdProductos;
    }

    public void setJdProductos(JDialog jdProductos) {
        this.jdProductos = jdProductos;
    }

    public JRadioButton getRbEditar() {
        return rbEditar;
    }

    public void setRbEditar(JRadioButton rbEditar) {
        this.rbEditar = rbEditar;
    }

    public JRadioButton getRbGenerar() {
        return rbGenerar;
    }

    public void setRbGenerar(JRadioButton rbGenerar) {
        this.rbGenerar = rbGenerar;
    }

    public JTextField getTxtCodPro() {
        return txtCodPro;
    }

    public void setTxtCodPro(JTextField txtCodPro) {
        this.txtCodPro = txtCodPro;
    }

    public JTextPane getTxtPrevista() {
        return txtPrevista;
    }

    public void setTxtPrevista(JTextPane txtPrevista) {
        this.txtPrevista = txtPrevista;
    }

    public JTextField getTxtPronombre() {
        return txtPronombre;
    }

    public void setTxtPronombre(JTextField txtPronombre) {
        this.txtPronombre = txtPronombre;
    }

    public JTextField getTxtProprecio() {
        return txtProprecio;
    }

    public void setTxtProprecio(JTextField txtProprecio) {
        this.txtProprecio = txtProprecio;
    }

    public JButton getBtProModif() {
        return btProModif;
    }

    public void setBtProModif(JButton btProModif) {
        this.btProModif = btProModif;
    }

    public JButton getBtProdelete() {
        return btProdelete;
    }

    public void setBtProdelete(JButton btProdelete) {
        this.btProdelete = btProdelete;
    }

    public JButton getBtPronuevo() {
        return btPronuevo;
    }

    public void setBtPronuevo(JButton btPronuevo) {
        this.btPronuevo = btPronuevo;
    }

    public JTable getTbProductos() {
        return tbProductos;
    }

    public void setTbProductos(JTable tbProductos) {
        this.tbProductos = tbProductos;
    }

    public JTextField getTxtBusqueda() {
        return txtBusqueda;
    }

    public void setTxtBusqueda(JTextField txtBusqueda) {
        this.txtBusqueda = txtBusqueda;
    }

    public JLabel getLbModificar() {
        return lbModificar;
    }

    public void setLbModificar(JLabel lbModificar) {
        this.lbModificar = lbModificar;
    }

    public JLabel getLbNuevo() {
        return lbNuevo;
    }

    public void setLbNuevo(JLabel lbNuevo) {
        this.lbNuevo = lbNuevo;
    }

    public JButton getBtAgregarModi() {
        return btAgregarModi;
    }

    public void setBtAgregarModi(JButton btAgregarModi) {
        this.btAgregarModi = btAgregarModi;
    }

    public JButton getBtSalir() {
        return btSalir;
    }

    public void setBtSalir(JButton btSalir) {
        this.btSalir = btSalir;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdProductos = new javax.swing.JDialog();
        btVerCategoria = new javax.swing.JButton();
        btAgregarModi = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        txtPronombre = new javax.swing.JTextField();
        txtProprecio = new javax.swing.JTextField();
        lbModificar = new javax.swing.JLabel();
        cbProCate = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPrevista = new javax.swing.JTextPane();
        btPrevisualizar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCodPro = new javax.swing.JTextField();
        rbGenerar = new javax.swing.JRadioButton();
        rbEditar = new javax.swing.JRadioButton();
        lbNuevo = new javax.swing.JLabel();
        lbopcionovligatorianombre = new javax.swing.JLabel();
        lbopcionobligatoriaprecio = new javax.swing.JLabel();
        lbopcionobligatorioselecco = new javax.swing.JLabel();
        jdGastos = new javax.swing.JDialog();
        txtcodG = new javax.swing.JTextField();
        lbTitulo = new javax.swing.JLabel();
        btAgregarModiG = new javax.swing.JButton();
        btSalirG = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        txtprecioG = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbFotoG = new javax.swing.JLabel();
        btCargarFotoG = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtdescripG = new javax.swing.JTextArea();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbSubtotalG = new javax.swing.JLabel();
        lbTotalG = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtCantidadG = new javax.swing.JTextField();
        dtFecha = new com.toedter.calendar.JDateChooser();
        lboopreciogasto = new javax.swing.JLabel();
        lboocgasto = new javax.swing.JLabel();
        lboodesgasto = new javax.swing.JLabel();
        btgCodProd = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btProdelete = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        btPronuevo = new javax.swing.JButton();
        btProModif = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        lbTotalProd = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btEliminarGastoC = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        btNuevoGC = new javax.swing.JButton();
        btModiGastoC = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cbFechasGastos = new javax.swing.JComboBox<>();
        dtDesdeGasato = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        lbdesdeGastos = new javax.swing.JLabel();
        lbhastaGastos = new javax.swing.JLabel();
        dtHastaGasto = new com.toedter.calendar.JDateChooser();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbGastos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButton38 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabla_factura_registro = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        lbTotalventas = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbFechasVentas = new javax.swing.JComboBox<>();
        dtDesdeVentas = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        lblDesdeVentas = new javax.swing.JLabel();
        lbHastaVentas = new javax.swing.JLabel();
        dtHastaVentas = new com.toedter.calendar.JDateChooser();
        btFecha = new javax.swing.JButton();
        lbErrores = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbTotalvendido = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton37 = new javax.swing.JButton();

        btVerCategoria.setText("VER CATEGORIAS");

        btAgregarModi.setText("AGREGAR");

        btSalir.setText("SALIR");

        txtProprecio.setPreferredSize(new java.awt.Dimension(7, 29));

        lbModificar.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 20)); // NOI18N
        lbModificar.setText("MODIFICAR PRODUCTO");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Precio:");

        jScrollPane1.setViewportView(txtPrevista);

        btPrevisualizar.setText("Previsualizar");

        jLabel10.setText("Categoria;");

        jLabel11.setText("Codigo:");

        txtCodPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodProActionPerformed(evt);
            }
        });

        rbGenerar.setSelected(true);
        rbGenerar.setText("Generar codigos aut.");

        rbEditar.setText("Editar codigo");

        lbNuevo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 20)); // NOI18N
        lbNuevo.setText("NUEVO PRODUCTO");

        lbopcionovligatorianombre.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbopcionovligatorianombre.setForeground(new java.awt.Color(255, 0, 0));

        lbopcionobligatoriaprecio.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbopcionobligatoriaprecio.setForeground(new java.awt.Color(204, 0, 0));

        lbopcionobligatorioselecco.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbopcionobligatorioselecco.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jdProductosLayout = new javax.swing.GroupLayout(jdProductos.getContentPane());
        jdProductos.getContentPane().setLayout(jdProductosLayout);
        jdProductosLayout.setHorizontalGroup(
            jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdProductosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdProductosLayout.createSequentialGroup()
                        .addComponent(lbModificar)
                        .addGap(18, 18, 18)
                        .addComponent(lbNuevo))
                    .addGroup(jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jdProductosLayout.createSequentialGroup()
                            .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAgregarModi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jdProductosLayout.createSequentialGroup()
                                .addGroup(jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jdProductosLayout.createSequentialGroup()
                                        .addComponent(txtPronombre, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbopcionovligatorianombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jdProductosLayout.createSequentialGroup()
                                        .addComponent(txtProprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbopcionobligatoriaprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jdProductosLayout.createSequentialGroup()
                                        .addComponent(txtCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbGenerar)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbEditar))))
                            .addGroup(jdProductosLayout.createSequentialGroup()
                                .addGroup(jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jdProductosLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel5)
                                        .addGap(307, 307, 307)
                                        .addComponent(jLabel10))
                                    .addComponent(btPrevisualizar))
                                .addGroup(jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jdProductosLayout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(btVerCategoria))
                                    .addGroup(jdProductosLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbProCate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jdProductosLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(lbopcionobligatorioselecco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jdProductosLayout.setVerticalGroup(
            jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdProductosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbGenerar)
                    .addComponent(rbEditar)
                    .addComponent(jLabel11)
                    .addComponent(txtCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdProductosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPronombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jdProductosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbopcionovligatorianombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProCate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtProprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(lbopcionobligatoriaprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbopcionobligatorioselecco, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPrevisualizar)
                    .addComponent(btVerCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jdProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAgregarModi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jdGastos.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcodG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodGActionPerformed(evt);
            }
        });
        jdGastos.getContentPane().add(txtcodG, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 73, 136, 33));

        lbTitulo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 20)); // NOI18N
        lbTitulo.setText("NUEVO GASTO");
        jdGastos.getContentPane().add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 22, -1, 33));

        btAgregarModiG.setText("AGREGAR");
        jdGastos.getContentPane().add(btAgregarModiG, new org.netbeans.lib.awtextra.AbsoluteConstraints(662, 483, 117, 50));

        btSalirG.setText("SALIR");
        jdGastos.getContentPane().add(btSalirG, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 495, 117, 50));

        jLabel21.setText("Codigo:");
        jdGastos.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 81, -1, -1));

        jLabel41.setText("Fecha:");
        jdGastos.getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 81, 43, -1));
        jdGastos.getContentPane().add(txtprecioG, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 316, 105, 44));

        jLabel6.setText("Foto de factura recibida por el proveedor");
        jdGastos.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 132, -1, -1));

        lbFotoG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jdGastos.getContentPane().add(lbFotoG, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 220, 231, 169));

        btCargarFotoG.setText("Cargar foto");
        jdGastos.getContentPane().add(btCargarFotoG, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 164, 122, 44));

        txtdescripG.setColumns(20);
        txtdescripG.setRows(5);
        jScrollPane3.setViewportView(txtdescripG);

        jdGastos.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 155, 331, 121));

        jLabel42.setText("Descripción:");
        jdGastos.getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 155, -1, -1));

        jLabel43.setText("Precio:");
        jdGastos.getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 330, -1, -1));

        jLabel19.setText("Subtotal:");
        jdGastos.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 385, -1, -1));

        jLabel22.setText("Total:");
        jdGastos.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 419, -1, -1));

        lbSubtotalG.setText("00.00");
        jdGastos.getContentPane().add(lbSubtotalG, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 385, -1, -1));

        lbTotalG.setText("00.00");
        jdGastos.getContentPane().add(lbTotalG, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 419, -1, -1));

        jLabel44.setText("Cantidad:");
        jdGastos.getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 330, -1, -1));
        jdGastos.getContentPane().add(txtCantidadG, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 316, 105, 44));
        jdGastos.getContentPane().add(dtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 73, 164, 33));

        lboopreciogasto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lboopreciogasto.setForeground(new java.awt.Color(255, 0, 0));
        jdGastos.getContentPane().add(lboopreciogasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 40, 30));

        lboocgasto.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lboocgasto.setForeground(new java.awt.Color(204, 0, 0));
        jdGastos.getContentPane().add(lboocgasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 50, 30));

        lboodesgasto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lboodesgasto.setForeground(new java.awt.Color(255, 0, 0));
        jdGastos.getContentPane().add(lboodesgasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 50, 30));

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1660, 800));

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTabbedPane1.setFont(new java.awt.Font("Yu Gothic", 1, 16)); // NOI18N

        jLabel17.setText("Para buscar ingresa o el nombre, codigo, o categoria:");

        btProdelete.setText("Eliminar prod.");

        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre del producto", "Precio Unitario", "Categoria", "Estado"
            }
        ));
        jScrollPane4.setViewportView(tbProductos);

        jButton24.setText("CARGAR DATOS");

        jButton25.setText("SALIR");

        jButton26.setText("VER DETALLES");

        btPronuevo.setText("Nuevo producto");

        btProModif.setText("Modificar prod.");

        jButton29.setText("GENERAR REPORTE");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Hay");

        lbTotalProd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTotalProd.setText("00");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("productos registrados.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton24)
                .addGap(18, 18, 18)
                .addComponent(jButton26)
                .addGap(18, 18, 18)
                .addComponent(jButton29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1115, Short.MAX_VALUE)
                .addComponent(jButton25)
                .addGap(32, 32, 32))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btPronuevo)
                .addGap(30, 30, 30)
                .addComponent(btProdelete)
                .addGap(26, 26, 26)
                .addComponent(btProModif)
                .addGap(52, 52, 52))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTotalProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btProdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btPronuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btProModif, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBusqueda))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel13)
                    .addComponent(lbTotalProd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Productos", jPanel4);

        btEliminarGastoC.setText("Eliminar gast.");

        jButton9.setText("CARGAR DATOS");

        jButton11.setText("SALIR");

        jButton12.setText("VER DETALLES");

        btNuevoGC.setText("Nuevo gasto");

        btModiGastoC.setText("Modificar gast.");

        jButton15.setText("GENERAR REPORTE");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Hay");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("00");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel26.setText("gastos registrados.");

        cbFechasGastos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbFechasGastos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoy", "Esta semana", "Este mes", "Periodo específico", "Día específico" }));

        jLabel1.setText("Busca los gastos en la fecha de:");

        lbdesdeGastos.setText("Desde:");

        lbhastaGastos.setText("Hasta:");

        jTextPane1.setEditable(false);
        jScrollPane5.setViewportView(jTextPane1);

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setText("TOTAL DE GASTOS:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("00");

        tbGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Descripcion", "Fecha", "Costo Unit.", "Cantidad", "Subtotal", "Total", "Foto"
            }
        ));
        jScrollPane2.setViewportView(tbGastos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1115, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbFechasGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtDesdeGasato, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbdesdeGastos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbhastaGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtHastaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btNuevoGC)
                .addGap(30, 30, 30)
                .addComponent(btEliminarGastoC)
                .addGap(26, 26, 26)
                .addComponent(btModiGastoC)
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addComponent(jLabel28)
                .addGap(52, 52, 52))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFechasGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btEliminarGastoC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btNuevoGC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btModiGastoC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbdesdeGastos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtDesdeGasato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbhastaGastos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtHastaGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 422, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(177, 177, 177)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(157, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Gastos", jPanel1);

        jButton38.setText("VER DETALLES");

        jButton41.setText("GENERAR REPORTE");

        jButton43.setText("CARGAR DATOS");

        tabla_factura_registro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FACTURA ID", "CLIENTE ID", "NOMBRES", "CEDULA", "FECHA", "TOTAL FACTURA"
            }
        ));
        jScrollPane6.setViewportView(tabla_factura_registro);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Hay");

        lbTotalventas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTotalventas.setText("00");

        cbFechasVentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbFechasVentas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hoy", "Esta semana", "Este mes", "Periodo específico", "Día específico" }));

        dtDesdeVentas.setDateFormatString("dd/MM/yyyy");

        jLabel3.setText("Busca los gastos en la fecha de:");

        lblDesdeVentas.setText("Desde:");

        lbHastaVentas.setText("Hasta:");

        btFecha.setText("Buscar por fecha");

        lbErrores.setForeground(new java.awt.Color(255, 0, 51));
        lbErrores.setText("Mensaje de error");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbFechasVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(262, 262, 262)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtDesdeVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDesdeVentas))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbHastaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtHastaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbErrores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addComponent(btFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(658, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblDesdeVentas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtDesdeVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFechasVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(lbHastaVentas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dtHastaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbErrores)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("facturas registradas");

        lbTotalvendido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTotalvendido.setText("00");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Total de ventas:  $");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton43)
                        .addGap(18, 18, 18)
                        .addComponent(jButton38)
                        .addGap(18, 18, 18)
                        .addComponent(jButton41))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalventas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTotalvendido)
                .addGap(142, 142, 142))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbTotalventas)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lbTotalvendido))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ventas", jPanel2);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel2.setText("Registros");

        jButton37.setText("SALIR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(708, 708, 708)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton37)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodProActionPerformed

    private void txtcodGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodGActionPerformed

    public ButtonGroup getBtgCodProd() {
        return btgCodProd;
    }

    public void setBtgCodProd(ButtonGroup btgCodProd) {
        this.btgCodProd = btgCodProd;
    }

    public JTable getTabla_factura_registro() {
        return tabla_factura_registro;
    }

    public void setTabla_factura_registro(JTable tabla_factura_registro) {
        this.tabla_factura_registro = tabla_factura_registro;
    }

    public JLabel getLbTotalProd() {
        return lbTotalProd;
    }

    public void setLbTotalProd(JLabel lbTotalProd) {
        this.lbTotalProd = lbTotalProd;
    }

    public JLabel getLbTotalventas() {
        return lbTotalventas;
    }

    public void setLbTotalventas(JLabel lbTotalventas) {
        this.lbTotalventas = lbTotalventas;
    }

    public JLabel getLbTotalvendido() {
        return lbTotalvendido;
    }

    public void setLbTotalvendido(JLabel lbTotalvendido) {
        this.lbTotalvendido = lbTotalvendido;
    }

    public JComboBox<String> getCbFechasGastos() {
        return cbFechasGastos;
    }

    public void setCbFechasGastos(JComboBox<String> cbFechasGastos) {
        this.cbFechasGastos = cbFechasGastos;
    }

    public JComboBox<String> getCbFechasVentas() {
        return cbFechasVentas;
    }

    public void setCbFechasVentas(JComboBox<String> cbFechasVentas) {
        this.cbFechasVentas = cbFechasVentas;
    }

    public JDateChooser getDtDesdeGasato() {
        return dtDesdeGasato;
    }

    public void setDtDesdeGasato(JDateChooser dtDesdeGasato) {
        this.dtDesdeGasato = dtDesdeGasato;
    }

    public JDateChooser getDtDesdeVentas() {
        return dtDesdeVentas;
    }

    public void setDtDesdeVentas(JDateChooser dtDesdeVentas) {
        this.dtDesdeVentas = dtDesdeVentas;
    }

    public JDateChooser getDtHastaGasto() {
        return dtHastaGasto;
    }

    public void setDtHastaGasto(JDateChooser dtHastaGasto) {
        this.dtHastaGasto = dtHastaGasto;
    }

    public JDateChooser getDtHastaVentas() {
        return dtHastaVentas;
    }

    public void setDtHastaVentas(JDateChooser dtHastaVentas) {
        this.dtHastaVentas = dtHastaVentas;
    }

    public JLabel getLbHastaVentas() {
        return lbHastaVentas;
    }

    public void setLbHastaVentas(JLabel lbHastaVentas) {
        this.lbHastaVentas = lbHastaVentas;
    }

    public JLabel getLbdesdeGastos() {
        return lbdesdeGastos;
    }

    public void setLbdesdeGastos(JLabel lbdesdeGastos) {
        this.lbdesdeGastos = lbdesdeGastos;
    }

    public JLabel getLbhastaGastos() {
        return lbhastaGastos;
    }

    public void setLbhastaGastos(JLabel lbhastaGastos) {
        this.lbhastaGastos = lbhastaGastos;
    }

    public JLabel getLblDesdeVentas() {
        return lblDesdeVentas;
    }

    public void setLblDesdeVentas(JLabel lblDesdeVentas) {
        this.lblDesdeVentas = lblDesdeVentas;
    }

    public JLabel getLbFotoG() {
        return lbFotoG;
    }

    public void setLbFotoG(JLabel lbFotoG) {
        this.lbFotoG = lbFotoG;
    }

    public JLabel getLbSubtotalG() {
        return lbSubtotalG;
    }

    public void setLbSubtotalG(JLabel lbSubtotalG) {
        this.lbSubtotalG = lbSubtotalG;
    }

    public JLabel getLbTitulo() {
        return lbTitulo;
    }

    public void setLbTitulo(JLabel lbTitulo) {
        this.lbTitulo = lbTitulo;
    }

    public JLabel getLbTotalG() {
        return lbTotalG;
    }

    public void setLbTotalG(JLabel lbTotalG) {
        this.lbTotalG = lbTotalG;
    }

    public JTable getTbGastos() {
        return tbGastos;
    }

    public void setTbGastos(JTable tbGastos) {
        this.tbGastos = tbGastos;
    }

    public JTextField getTxtCantidadG() {
        return txtCantidadG;
    }

    public void setTxtCantidadG(JTextField txtCantidadG) {
        this.txtCantidadG = txtCantidadG;
    }

    public JTextField getTxtcodG() {
        return txtcodG;
    }

    public void setTxtcodG(JTextField txtcodG) {
        this.txtcodG = txtcodG;
    }

    public JTextArea getTxtdescripG() {
        return txtdescripG;
    }

    public void setTxtdescripG(JTextArea txtdescripG) {
        this.txtdescripG = txtdescripG;
    }

    public JTextField getTxtprecioG() {
        return txtprecioG;
    }

    public void setTxtprecioG(JTextField txtprecioG) {
        this.txtprecioG = txtprecioG;
    }

    public JButton getBtAgregarModiG() {
        return btAgregarModiG;
    }

    public void setBtAgregarModiG(JButton btAgregarModiG) {
        this.btAgregarModiG = btAgregarModiG;
    }

    public JButton getBtCargarFotoG() {
        return btCargarFotoG;
    }

    public void setBtCargarFotoG(JButton btCargarFotoG) {
        this.btCargarFotoG = btCargarFotoG;
    }

    public JButton getBtEliminarGastoC() {
        return btProdelete;
    }

    public void setBtEliminarGastoC(JButton btEliminarGastoC) {
        this.btProdelete = btEliminarGastoC;
    }

    public JButton getBtModiGastoC() {
        return btProModif;
    }

    public void setBtModiGastoC(JButton btModiGastoC) {
        this.btProModif = btModiGastoC;
    }

    public JButton getBtNuevoGC() {
        return btPronuevo;
    }

    public void setBtNuevoGC(JButton btNuevoGC) {
        this.btPronuevo = btNuevoGC;
    }

    public JButton getBtSalirG() {
        return btSalirG;
    }

    public void setBtSalirG(JButton btSalirG) {
        this.btSalirG = btSalirG;
    }

    public JDateChooser getDtFecha() {
        return dtFecha;
    }

    public void setDtFecha(JDateChooser dtFecha) {
        this.dtFecha = dtFecha;
    }

    public JButton getBtFecha() {
        return btFecha;
    }

    public void setBtFecha(JButton btFecha) {
        this.btFecha = btFecha;
    }

    public JLabel getLbErrores() {
        return lbErrores;
    }

    public void setLbErrores(JLabel lbErrores) {
        this.lbErrores = lbErrores;
    }

    public JLabel getLbopcionobligatoriaprecio() {
        return lbopcionobligatoriaprecio;
    }

    public void setLbopcionobligatoriaprecio(JLabel lbopcionobligatoriaprecio) {
        this.lbopcionobligatoriaprecio = lbopcionobligatoriaprecio;
    }

    public JLabel getLbopcionobligatorioselecco() {
        return lbopcionobligatorioselecco;
    }

    public void setLbopcionobligatorioselecco(JLabel lbopcionobligatorioselecco) {
        this.lbopcionobligatorioselecco = lbopcionobligatorioselecco;
    }

    public JLabel getLbopcionovligatorianombre() {
        return lbopcionovligatorianombre;
    }

    public void setLbopcionovligatorianombre(JLabel lbopcionovligatorianombre) {
        this.lbopcionovligatorianombre = lbopcionovligatorianombre;
    }

    public JLabel getLboocgasto() {
        return lboocgasto;
    }

    public void setLboocgasto(JLabel lboocgasto) {
        this.lboocgasto = lboocgasto;
    }

    public JLabel getLboopreciogasto() {
        return lboopreciogasto;
    }

    public void setLboopreciogasto(JLabel lboopreciogasto) {
        this.lboopreciogasto = lboopreciogasto;
    }

    public JLabel getLboodesgasto() {
        return lboodesgasto;
    }

    public void setLboodesgasto(JLabel lboodesgasto) {
        this.lboodesgasto = lboodesgasto;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarModi;
    private javax.swing.JButton btAgregarModiG;
    private javax.swing.JButton btCargarFotoG;
    private javax.swing.JButton btEliminarGastoC;
    private javax.swing.JButton btFecha;
    private javax.swing.JButton btModiGastoC;
    private javax.swing.JButton btNuevoGC;
    private javax.swing.JButton btPrevisualizar;
    private javax.swing.JButton btProModif;
    private javax.swing.JButton btProdelete;
    private javax.swing.JButton btPronuevo;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btSalirG;
    private javax.swing.JButton btVerCategoria;
    private javax.swing.ButtonGroup btgCodProd;
    private javax.swing.JComboBox<String> cbFechasGastos;
    private javax.swing.JComboBox<String> cbFechasVentas;
    private javax.swing.JComboBox<String> cbProCate;
    private com.toedter.calendar.JDateChooser dtDesdeGasato;
    private com.toedter.calendar.JDateChooser dtDesdeVentas;
    private com.toedter.calendar.JDateChooser dtFecha;
    private com.toedter.calendar.JDateChooser dtHastaGasto;
    private com.toedter.calendar.JDateChooser dtHastaVentas;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JDialog jdGastos;
    private javax.swing.JDialog jdProductos;
    private javax.swing.JLabel lbErrores;
    private javax.swing.JLabel lbFotoG;
    private javax.swing.JLabel lbHastaVentas;
    private javax.swing.JLabel lbModificar;
    private javax.swing.JLabel lbNuevo;
    private javax.swing.JLabel lbSubtotalG;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTotalG;
    private javax.swing.JLabel lbTotalProd;
    private javax.swing.JLabel lbTotalvendido;
    private javax.swing.JLabel lbTotalventas;
    private javax.swing.JLabel lbdesdeGastos;
    private javax.swing.JLabel lbhastaGastos;
    private javax.swing.JLabel lblDesdeVentas;
    private javax.swing.JLabel lboocgasto;
    private javax.swing.JLabel lboodesgasto;
    private javax.swing.JLabel lboopreciogasto;
    private javax.swing.JLabel lbopcionobligatoriaprecio;
    private javax.swing.JLabel lbopcionobligatorioselecco;
    private javax.swing.JLabel lbopcionovligatorianombre;
    private javax.swing.JRadioButton rbEditar;
    private javax.swing.JRadioButton rbGenerar;
    private javax.swing.JTable tabla_factura_registro;
    private javax.swing.JTable tbGastos;
    private javax.swing.JTable tbProductos;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCantidadG;
    private javax.swing.JTextField txtCodPro;
    private javax.swing.JTextPane txtPrevista;
    private javax.swing.JTextField txtPronombre;
    private javax.swing.JTextField txtProprecio;
    private javax.swing.JTextField txtcodG;
    private javax.swing.JTextArea txtdescripG;
    private javax.swing.JTextField txtprecioG;
    // End of variables declaration//GEN-END:variables
}
