/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIsta;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JToolBar;

/**
 *
 * @author Abel Gomez
 */
public class vistamenuprincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistamenuprincipal
     */
    public vistamenuprincipal() {
        initComponents();
    }

    public JButton getBtncrudclientes() {
        return btncrudclientes;
    }

    public void setBtncrudclientes(JButton btncrudclientes) {
        this.btncrudclientes = btncrudclientes;
    }

    public JToolBar getjToolBar1() {
        return jToolBar1;
    }

    public void setjToolBar1(JToolBar jToolBar1) {
        this.jToolBar1 = jToolBar1;
    }

    public JButton getBtn_pedido_pastel() {
        return btn_pedido_pastel;
    }

    public void setBtn_pedido_pastel(JButton btn_pedido_pastel) {
        this.btn_pedido_pastel = btn_pedido_pastel;
    }

    public JButton getBtn_cotizacion() {
        return btn_cotizacion;
    }

    public void setBtn_cotizacion(JButton btn_cotizacion) {
        this.btn_cotizacion = btn_cotizacion;
    }

    public JButton getBtn_factura() {
        return btn_factura;
    }

    public void setBtn_factura(JButton btn_factura) {
        this.btn_factura = btn_factura;
    }


    public JButton getBtn_registro_factu() {
        return btn_registro_factu;
    }

    public void setBtn_registro_factu(JButton btn_registro_factu) {
        this.btn_registro_factu = btn_registro_factu;
    }

    public JDesktopPane getJdpprincipal() {
        return jdpprincipal;
    }

    public void setJdpprincipal(JDesktopPane jdpprincipal) {
        this.jdpprincipal = jdpprincipal;
    }

    public JButton getBtncrudproveedores() {
        return btncrudproveedores;
    }

    public void setBtncrudproveedores(JButton btncrudproveedores) {
        this.btncrudproveedores = btncrudproveedores;
    }

    public JButton getBtProductos() {
        return btProductos;
    }

    public void setBtProductos(JButton btProductos) {
        this.btProductos = btProductos;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_cotizacion = new javax.swing.JButton();
        btProductos = new javax.swing.JButton();
        btncrudproveedores = new javax.swing.JButton();
        btncrudclientes = new javax.swing.JButton();
        btn_pedido_pastel = new javax.swing.JButton();
        btn_factura = new javax.swing.JButton();
        btn_registro_factu = new javax.swing.JButton();
        jdpprincipal = new javax.swing.JDesktopPane();
        jToolBar2 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(null);
        jToolBar1.setRollover(true);

        btn_cotizacion.setBackground(new java.awt.Color(255, 255, 255));
        btn_cotizacion.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btn_cotizacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconoseImagenes/cootizar.png"))); // NOI18N
        btn_cotizacion.setText("Cootizacion");
        btn_cotizacion.setBorderPainted(false);
        btn_cotizacion.setFocusable(false);
        btn_cotizacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cotizacion.setMargin(new java.awt.Insets(2, 14, 2, 16));
        btn_cotizacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_cotizacion);

        btProductos.setBackground(new java.awt.Color(255, 255, 255));
        btProductos.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconoseImagenes/productos.png"))); // NOI18N
        btProductos.setText("Registros");
        btProductos.setBorderPainted(false);
        btProductos.setFocusable(false);
        btProductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btProductos.setMargin(new java.awt.Insets(2, 14, 2, 16));
        btProductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btProductos);

        btncrudproveedores.setBackground(new java.awt.Color(255, 255, 255));
        btncrudproveedores.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btncrudproveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconoseImagenes/proveedor.png"))); // NOI18N
        btncrudproveedores.setText("Proveedor");
        btncrudproveedores.setBorderPainted(false);
        btncrudproveedores.setFocusable(false);
        btncrudproveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncrudproveedores.setMargin(new java.awt.Insets(2, 14, 2, 16));
        btncrudproveedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btncrudproveedores);

        btncrudclientes.setBackground(new java.awt.Color(255, 255, 255));
        btncrudclientes.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        btncrudclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconoseImagenes/user_group_50px.png"))); // NOI18N
        btncrudclientes.setText("Cliente");
        btncrudclientes.setBorderPainted(false);
        btncrudclientes.setFocusable(false);
        btncrudclientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncrudclientes.setMargin(new java.awt.Insets(2, 14, 2, 16));
        btncrudclientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btncrudclientes);

        btn_pedido_pastel.setText("Pedidos");
        btn_pedido_pastel.setFocusable(false);
        btn_pedido_pastel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_pedido_pastel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_pedido_pastel);

        btn_factura.setText("factura");
        btn_factura.setFocusable(false);
        btn_factura.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_factura.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_factura);

        btn_registro_factu.setText("Registro de facturas");
        btn_registro_factu.setFocusable(false);
        btn_registro_factu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_registro_factu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_registro_factu);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 720, 90));

        jdpprincipal.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jdpprincipalLayout = new javax.swing.GroupLayout(jdpprincipal);
        jdpprincipal.setLayout(jdpprincipalLayout);
        jdpprincipalLayout.setHorizontalGroup(
            jdpprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1680, Short.MAX_VALUE)
        );
        jdpprincipalLayout.setVerticalGroup(
            jdpprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );

        getContentPane().add(jdpprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1680, 840));

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setBorder(null);
        jToolBar2.setRollover(true);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconoseImagenes/home.png"))); // NOI18N
        jButton2.setText("Inicio");
        jButton2.setBorderPainted(false);
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMargin(new java.awt.Insets(2, 14, 2, 16));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton2);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconoseImagenes/salir.png"))); // NOI18N
        jButton3.setText("Salir");
        jButton3.setBorderPainted(false);
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMargin(new java.awt.Insets(2, 14, 2, 16));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jButton3);

        getContentPane().add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 90));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(vistamenuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(vistamenuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(vistamenuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(vistamenuprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new vistamenuprincipal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btProductos;
    private javax.swing.JButton btn_cotizacion;
    private javax.swing.JButton btn_factura;
    private javax.swing.JButton btn_pedido_pastel;
    private javax.swing.JButton btn_registro_factu;
    private javax.swing.JButton btncrudclientes;
    private javax.swing.JButton btncrudproveedores;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JDesktopPane jdpprincipal;
    // End of variables declaration//GEN-END:variables
}
