/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIsta;

import com.toedter.calendar.JDateChooser;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author carlos
 */
public class Vista_pedidoPastel extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_pedidoPastel
     */
    public Vista_pedidoPastel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialog_pedido = new javax.swing.JDialog();
        label_titulo = new javax.swing.JLabel();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        txt_id_pedido = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txt_nombre_producto = new javax.swing.JTextField();
        btn_buscar_producto = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txt_producto_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_abono = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        btn_examinar_foto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        label_foto_pedido = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_area_especificacion = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        btn_buscar_cliente = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_apellido_cliente = new javax.swing.JTextField();
        txt_nombre_cliente = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_id_cliente = new javax.swing.JTextField();
        date_fecha_entrega = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        date_fecha_pedido = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        dialog_buscar_cliente = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        txt_buscar_cliente = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_cliente_pedido = new javax.swing.JTable();
        btb_cargar_cliente = new javax.swing.JButton();
        btn_cancelar_cliente = new javax.swing.JButton();
        dialog_buscar_producto = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_productos = new javax.swing.JTable();
        btn_aceptar_producto = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_buscar_producto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_busquedapedido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_eliminar_pedido = new javax.swing.JButton();
        btn_aagregar_pedido = new javax.swing.JButton();
        btn_modificar_pedido = new javax.swing.JButton();
        btn_nuevo_cliente = new javax.swing.JButton();
        btn_nuevo_producto = new javax.swing.JButton();
        btn_ver_detalles = new javax.swing.JButton();
        btn_actualizar_tabla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_pedido = new javax.swing.JTable();

        label_titulo.setText("Pedidos de prodcutos");

        btn_aceptar.setText("Aceptar");

        btn_cancelar.setText("Cancelar");

        txt_id_pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_pedidoActionPerformed(evt);
            }
        });

        btn_buscar_producto.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btn_buscar_producto.setText("Buscar Producto");

        jLabel13.setText("ID Prd.");

        jLabel4.setText("Producto");

        jLabel8.setText("Porciones o cantidad");

        jLabel9.setText("Abono");

        btn_examinar_foto.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btn_examinar_foto.setText("Cargar Foto");

        jLabel10.setText("Foto del Pedido");

        label_foto_pedido.setBackground(new java.awt.Color(0, 0, 0));
        label_foto_pedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("Especificacion");

        txt_area_especificacion.setColumns(20);
        txt_area_especificacion.setRows(5);
        jScrollPane2.setViewportView(txt_area_especificacion);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_buscar_producto)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13)
                                    .addComponent(txt_producto_id, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_nombre_producto)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(51, 51, 51)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txt_abono, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_foto_pedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(35, 35, 35)))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_examinar_foto)
                        .addGap(66, 66, 66))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_foto_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_examinar_foto))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_producto_id, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscar_producto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_abono, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(13, 13, 13)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_buscar_cliente.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btn_buscar_cliente.setText("Buscar Cliente");

        jLabel11.setText("Apellido");

        jLabel7.setText("Nombre");

        jLabel12.setText("ID Client.");

        jLabel6.setText("Fecha de Entrega");

        jLabel5.setText("Fecha del Pedido");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btn_buscar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txt_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_nombre_cliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txt_apellido_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(date_fecha_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(date_fecha_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_fecha_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(date_fecha_entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_apellido_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar_cliente))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout dialog_pedidoLayout = new javax.swing.GroupLayout(dialog_pedido.getContentPane());
        dialog_pedido.getContentPane().setLayout(dialog_pedidoLayout);
        dialog_pedidoLayout.setHorizontalGroup(
            dialog_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_pedidoLayout.createSequentialGroup()
                .addGroup(dialog_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(dialog_pedidoLayout.createSequentialGroup()
                .addGroup(dialog_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_pedidoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_id_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialog_pedidoLayout.createSequentialGroup()
                        .addGroup(dialog_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialog_pedidoLayout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addComponent(btn_aceptar)
                                .addGap(62, 62, 62)
                                .addComponent(btn_cancelar))
                            .addGroup(dialog_pedidoLayout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addComponent(label_titulo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dialog_pedidoLayout.setVerticalGroup(
            dialog_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_pedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_id_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialog_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_cancelar))
                .addGap(50, 50, 50))
        );

        jLabel15.setText("Lista Cliente");

        tabla_cliente_pedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cliente id", "Cedula", "Nombre", "Apellido"
            }
        ));
        jScrollPane3.setViewportView(tabla_cliente_pedido);

        btb_cargar_cliente.setText("Cargar Datos");

        btn_cancelar_cliente.setText("Cancelar");

        javax.swing.GroupLayout dialog_buscar_clienteLayout = new javax.swing.GroupLayout(dialog_buscar_cliente.getContentPane());
        dialog_buscar_cliente.getContentPane().setLayout(dialog_buscar_clienteLayout);
        dialog_buscar_clienteLayout.setHorizontalGroup(
            dialog_buscar_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_buscar_clienteLayout.createSequentialGroup()
                .addGroup(dialog_buscar_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_buscar_clienteLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel15))
                    .addGroup(dialog_buscar_clienteLayout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(txt_buscar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialog_buscar_clienteLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialog_buscar_clienteLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btb_cargar_cliente)
                        .addGap(37, 37, 37)
                        .addComponent(btn_cancelar_cliente)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        dialog_buscar_clienteLayout.setVerticalGroup(
            dialog_buscar_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_buscar_clienteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addGap(31, 31, 31)
                .addComponent(txt_buscar_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(dialog_buscar_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btb_cargar_cliente)
                    .addComponent(btn_cancelar_cliente))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jLabel16.setText("Tabla Productos");

        tabla_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Producto Id", "Nombre Producto", "Precio"
            }
        ));
        jScrollPane4.setViewportView(tabla_productos);

        btn_aceptar_producto.setText("Aceptar");

        jButton1.setText("Cancelar");

        javax.swing.GroupLayout dialog_buscar_productoLayout = new javax.swing.GroupLayout(dialog_buscar_producto.getContentPane());
        dialog_buscar_producto.getContentPane().setLayout(dialog_buscar_productoLayout);
        dialog_buscar_productoLayout.setHorizontalGroup(
            dialog_buscar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_buscar_productoLayout.createSequentialGroup()
                .addGroup(dialog_buscar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialog_buscar_productoLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btn_aceptar_producto)
                        .addGap(80, 80, 80)
                        .addComponent(jButton1))
                    .addGroup(dialog_buscar_productoLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialog_buscar_productoLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel16))
                    .addGroup(dialog_buscar_productoLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(txt_buscar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        dialog_buscar_productoLayout.setVerticalGroup(
            dialog_buscar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialog_buscar_productoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel16)
                .addGap(23, 23, 23)
                .addComponent(txt_buscar_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialog_buscar_productoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar_producto)
                    .addComponent(jButton1))
                .addGap(97, 97, 97))
        );

        setBackground(new java.awt.Color(148, 180, 159));
        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1660, 800));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel2.setText("Pedidos de pasteles");

        jPanel1.setBackground(new java.awt.Color(148, 180, 159));

        jLabel1.setText("Ingrese un dato para buscar:");

        jLabel3.setText("Ordenar por:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_busquedapedido, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(176, 176, 176)
                        .addComponent(jLabel3)))
                .addContainerGap(765, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_busquedapedido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        btn_eliminar_pedido.setText("Eliminar pedido");

        btn_aagregar_pedido.setText("+ Nuevo pedido");

        btn_modificar_pedido.setText("Modificar pedido");

        btn_nuevo_cliente.setText("+ Nuevo cliente");

        btn_nuevo_producto.setText("+ Nuevo producto");

        btn_ver_detalles.setText("Ver detalles");

        btn_actualizar_tabla.setText("Actualizar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_nuevo_producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_nuevo_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_actualizar_tabla, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_eliminar_pedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_modificar_pedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_aagregar_pedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ver_detalles, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(8, 8, 8))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_aagregar_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_modificar_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminar_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ver_detalles, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_actualizar_tabla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(btn_nuevo_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_nuevo_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );

        tabla_pedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Fecha de pedido", "Fecha de entrega", "Cliente", "Producto", "Cantidad", "Especificacion", "Abono", "Estado", "Foto"
            }
        ));
        jScrollPane1.setViewportView(tabla_pedido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(176, 176, 176))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(365, 365, 365))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_id_pedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_pedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_pedidoActionPerformed

    public JButton getBtn_buscar_producto() {
        return btn_buscar_producto;
    }

    public void setBtn_buscar_producto(JButton btn_buscar_producto) {
        this.btn_buscar_producto = btn_buscar_producto;
    }

    
    public JButton getBtb_cargar_cliente() {
        return btb_cargar_cliente;
    }

    public JButton getBtn_aceptar_producto() {
        return btn_aceptar_producto;
    }

    public void setBtn_aceptar_producto(JButton btn_aceptar_producto) {
        this.btn_aceptar_producto = btn_aceptar_producto;
    }

    public JTable getTabla_productos() {
        return tabla_productos;
    }

    public void setTabla_productos(JTable tabla_productos) {
        this.tabla_productos = tabla_productos;
    }

    public JTextField getTxt_busquedapedido() {
        return txt_busquedapedido;
    }

    public void setTxt_busquedapedido(JTextField txt_busquedapedido) {
        this.txt_busquedapedido = txt_busquedapedido;
    }

    public JTextField getTxt_buscar_producto() {
        return txt_buscar_producto;
    }

    public void setTxt_buscar_producto(JTextField txt_buscar_producto) {
        this.txt_buscar_producto = txt_buscar_producto;
    }

    
    public JButton getBtn_buscar_cliente() {
        return btn_buscar_cliente;
    }

    public void setBtn_buscar_cliente(JButton btn_buscar_cliente) {
        this.btn_buscar_cliente = btn_buscar_cliente;
    }

    
    public void setBtb_cargar_cliente(JButton btb_cargar_cliente) {
        this.btb_cargar_cliente = btb_cargar_cliente;
    }

    public JButton getBtn_cancelar_cliente() {
        return btn_cancelar_cliente;
    }

    public void setBtn_cancelar_cliente(JButton btn_cancelar_cliente) {
        this.btn_cancelar_cliente = btn_cancelar_cliente;
    }

    public JDialog getDialog_buscar_cliente() {
        return dialog_buscar_cliente;
    }

    public void setDialog_buscar_cliente(JDialog dialog_buscar_cliente) {
        this.dialog_buscar_cliente = dialog_buscar_cliente;
    }

    public JButton getBtn_actualizar_tabla() {
        return btn_actualizar_tabla;
    }

    public void setBtn_actualizar_tabla(JButton btn_actualizar_tabla) {
        this.btn_actualizar_tabla = btn_actualizar_tabla;
    }

    public JTable getTabla_cliente_pedido() {
        return tabla_cliente_pedido;
    }

    public void setTabla_cliente_pedido(JTable tabla_cliente_pedido) {
        this.tabla_cliente_pedido = tabla_cliente_pedido;
    }

    public JTextField getTxt_buscar_cliente() {
        return txt_buscar_cliente;
    }

    public void setTxt_buscar_cliente(JTextField txt_buscar_cliente) {
        this.txt_buscar_cliente = txt_buscar_cliente;
    }

    public JDialog getDialog_buscar_producto() {
        return dialog_buscar_producto;
    }

    public void setDialog_buscar_producto(JDialog dialog_buscar_producto) {
        this.dialog_buscar_producto = dialog_buscar_producto;
    }

    public JTextField getTxt_nombre_producto() {
        return txt_nombre_producto;
    }

    public void setTxt_nombre_producto(JTextField txt_nombre_producto) {
        this.txt_nombre_producto = txt_nombre_producto;
    }

    
    

    public JButton getBtn_aagregar_pedido() {
        return btn_aagregar_pedido;
    }

    public void setBtn_aagregar_pedido(JButton btn_aagregar_pedido) {
        this.btn_aagregar_pedido = btn_aagregar_pedido;
    }

    public JButton getBtn_aceptar() {
        return btn_aceptar;
    }

    public void setBtn_aceptar(JButton btn_aceptar) {
        this.btn_aceptar = btn_aceptar;
    }

    public JButton getBtn_cancelar() {
        return btn_cancelar;
    }

    public void setBtn_cancelar(JButton btn_cancelar) {
        this.btn_cancelar = btn_cancelar;
    }

    public JButton getBtn_eliminar_pedido() {
        return btn_eliminar_pedido;
    }

    public void setBtn_eliminar_pedido(JButton btn_eliminar_pedido) {
        this.btn_eliminar_pedido = btn_eliminar_pedido;
    }

    public JButton getBtn_modificar_pedido() {
        return btn_modificar_pedido;
    }

    public void setBtn_modificar_pedido(JButton btn_modificar_pedido) {
        this.btn_modificar_pedido = btn_modificar_pedido;
    }

    public JButton getBtn_nuevo_cliente() {
        return btn_nuevo_cliente;
    }

    public void setBtn_nuevo_cliente(JButton btn_nuevo_cliente) {
        this.btn_nuevo_cliente = btn_nuevo_cliente;
    }

    public JButton getBtn_nuevo_producto() {
        return btn_nuevo_producto;
    }

    public void setBtn_nuevo_producto(JButton btn_nuevo_producto) {
        this.btn_nuevo_producto = btn_nuevo_producto;
    }

    public JButton getBtn_ver_detalles() {
        return btn_ver_detalles;
    }

    public void setBtn_ver_detalles(JButton btn_ver_detalles) {
        this.btn_ver_detalles = btn_ver_detalles;
    }

    public JDateChooser getDate_fecha_entrega() {
        return date_fecha_entrega;
    }

    public void setDate_fecha_entrega(JDateChooser date_fecha_entrega) {
        this.date_fecha_entrega = date_fecha_entrega;
    }

    public JDateChooser getDate_fecha_pedido() {
        return date_fecha_pedido;
    }

    public void setDate_fecha_pedido(JDateChooser date_fecha_pedido) {
        this.date_fecha_pedido = date_fecha_pedido;
    }

    public JDialog getDialog_pedido() {
        return dialog_pedido;
    }

    public void setDialog_pedido(JDialog dialog_pedido) {
        this.dialog_pedido = dialog_pedido;
    }

    public JLabel getLabel_foto_pedido() {
        return label_foto_pedido;
    }

    public void setLabel_foto_pedido(JLabel label_foto_pedido) {
        this.label_foto_pedido = label_foto_pedido;
    }

    public JLabel getLabel_titulo() {
        return label_titulo;
    }

    public void setLabel_titulo(JLabel label_titulo) {
        this.label_titulo = label_titulo;
    }

    public JTextField getTxt_cantidad() {
        return txt_cantidad;
    }

    public void setTxt_cantidad(JTextField txt_cantidad) {
        this.txt_cantidad = txt_cantidad;
    }

    public JButton getBtn_examinar_foto() {
        return btn_examinar_foto;
    }

    public void setBtn_examinar_foto(JButton btn_examinar_foto) {
        this.btn_examinar_foto = btn_examinar_foto;
    }

   

    public JTable getTabla_pedido() {
        return tabla_pedido;
    }

    public void setTabla_pedido(JTable tabla_pedido) {
        this.tabla_pedido = tabla_pedido;
    }

    public JTextField getTxt_abono() {
        return txt_abono;
    }

    public void setTxt_abono(JTextField txt_abono) {
        this.txt_abono = txt_abono;
    }

    public JTextField getTxt_apellido_cliente() {
        return txt_apellido_cliente;
    }

    public void setTxt_apellido_cliente(JTextField txt_apellido_cliente) {
        this.txt_apellido_cliente = txt_apellido_cliente;
    }

    public JTextArea getTxt_area_especificacion() {
        return txt_area_especificacion;
    }

    public void setTxt_area_especificacion(JTextArea txt_area_especificacion) {
        this.txt_area_especificacion = txt_area_especificacion;
    }

    public JTextField getTxt_id_cliente() {
        return txt_id_cliente;
    }

    public void setTxt_id_cliente(JTextField txt_id_cliente) {
        this.txt_id_cliente = txt_id_cliente;
    }

    public JTextField getTxt_id_pedido() {
        return txt_id_pedido;
    }

    public void setTxt_id_pedido(JTextField txt_id_pedido) {
        this.txt_id_pedido = txt_id_pedido;
    }

    public JTextField getTxt_nombre_cliente() {
        return txt_nombre_cliente;
    }

    public void setTxt_nombre_cliente(JTextField txt_nombre_cliente) {
        this.txt_nombre_cliente = txt_nombre_cliente;
    }

    public JTextField getTxt_producto_id() {
        return txt_producto_id;
    }

    public void setTxt_producto_id(JTextField txt_producto_id) {
        this.txt_producto_id = txt_producto_id;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btb_cargar_cliente;
    private javax.swing.JButton btn_aagregar_pedido;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_aceptar_producto;
    private javax.swing.JButton btn_actualizar_tabla;
    private javax.swing.JButton btn_buscar_cliente;
    private javax.swing.JButton btn_buscar_producto;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_cancelar_cliente;
    private javax.swing.JButton btn_eliminar_pedido;
    private javax.swing.JButton btn_examinar_foto;
    private javax.swing.JButton btn_modificar_pedido;
    private javax.swing.JButton btn_nuevo_cliente;
    private javax.swing.JButton btn_nuevo_producto;
    private javax.swing.JButton btn_ver_detalles;
    private com.toedter.calendar.JDateChooser date_fecha_entrega;
    private com.toedter.calendar.JDateChooser date_fecha_pedido;
    private javax.swing.JDialog dialog_buscar_cliente;
    private javax.swing.JDialog dialog_buscar_producto;
    private javax.swing.JDialog dialog_pedido;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_foto_pedido;
    private javax.swing.JLabel label_titulo;
    private javax.swing.JTable tabla_cliente_pedido;
    private javax.swing.JTable tabla_pedido;
    private javax.swing.JTable tabla_productos;
    private javax.swing.JTextField txt_abono;
    private javax.swing.JTextField txt_apellido_cliente;
    private javax.swing.JTextArea txt_area_especificacion;
    private javax.swing.JTextField txt_buscar_cliente;
    private javax.swing.JTextField txt_buscar_producto;
    private javax.swing.JTextField txt_busquedapedido;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_id_cliente;
    private javax.swing.JTextField txt_id_pedido;
    private javax.swing.JTextField txt_nombre_cliente;
    private javax.swing.JTextField txt_nombre_producto;
    private javax.swing.JTextField txt_producto_id;
    // End of variables declaration//GEN-END:variables
}
